### ISSUE TITLE
not an issue at all, just some ideas

### ISSUE THREAD

**Issue by napisani** [smartpde/neoscopes#4]
Hi there, 
just want to start by saying - i love this plugin and the idea behind it. I had been looking for something like this for a while.
I  have some ideas I want to pass by you and see if you think they belong as either
1. built in plugin features
2. customized lua configuration

First thought: one feature I always find myself looking for is a "scope" that represents only the files that have changed from my current git index when compared to 'origin/main'. I hacked a neoscopes and telescope configuration together to get it to work the way i envisioned but i'm wondering if there is an opportunity for a core feature here.

here is a screen cast:

https://user-images.githubusercontent.com/426949/210155956-daaa9671-750c-4ec2-aba7-867bd6763ba3.mov

here is the relevant config
```lua
local status_ok, scopes = pcall(require, "neoscopes")
if not status_ok then
	vim.notify("neoscopes not found ")
	return
end

scopes.add({
	name = "ROOT",
	dirs = {},
})
local function populate_with_files_in_diff(rule, to, from)
	rule.dirs = {}
	local handle = io.popen("git diff --name-only --relative " .. to .. ".." .. from)
	if handle ~= nil then
		local result = handle:read("*a")
		for line in result:gmatch("[^\r\n]+") do
			table.insert(rule.dirs, "file:///" .. line)
		end
		handle:close()
	end
end
local cmp_origin_main_scope = {
	name = "origin/main <-> this",
	dirs = {},
}

cmp_origin_main_scope["on_select"] = function()
	populate_with_files_in_diff(cmp_origin_main_scope, "origin/main", "")
end

scopes.add(cmp_origin_main_scope)

-- end of neoscopes config...
-- start of telescope config...

local neoscopes = require("neoscopes")
local function constrain_to_scope()
	local success, dirs = pcall(neoscopes.get_current_dirs)
	if not success or not dirs or next(dirs) == nil then
		return { "./" }, {}
	end
	local find_command_opts = {}
	local search_dir_opts = { "./" }
	local pattern = "^file:///"
	for _, dir_name in ipairs(dirs) do
		if dir_name then
			if dir_name:find(pattern) ~= nil then
				table.insert(find_command_opts, "--iglob")
				local file_name = dir_name:gsub(pattern, "")
				table.insert(find_command_opts, file_name)
			else
				table.insert(search_dir_opts, dir_name)
			end
		end
	end
	return find_command_opts, search_dir_opts
end

function M.find_files_from_root(opts)
	opts = opts or {}
	opts.cwd = rooter.get_root_dir()
	local cmd_opts, dir_opts = constrain_to_scope()
	opts.find_command = utils.table_merge(
		utils.table_merge({
			"rg",
			"--files",
			"--hidden",
			"--no-ignore", 
		}, ignore_globs),
		cmd_opts
	)
	opts.search_dirs = opts.search_dirs or {}
	opts.search_dirs = utils.table_merge(opts.search_dirs, dir_opts)
	-- utils.print(opts)
	builtin.find_files(opts)
end
```

Second idea: for monorepo projects that use npm (or an npm replacement), maybe we can add support for parsing the `package.json` file (if available in the cwd) and if there are `workspaces` defined then, create a scope for each workspace.

I'm really curious to hear you thoughts.

~Nick

**Comment by defr0std** [comment]
Hi Nick,

Thanks for reaching out, very interesting topics.

Regarding git changed files, I think it introduces a couple of new use cases:
1. A scope being a mix of directories and files. Currently, a scope is a collection of directories, but in this case it is a collection of files.  There is no reason why a scope can't be a mix of those. This way you wound't need to use the file:// scheme, but just add the files to the designated scope property.
2. A callback for updating the scope dynamically. Instead of adding the scope contents in the on_select callback, it would be better to add some other callback (e.g. on_update) which would be invoked "when needed". For example, when listing the scope in the Telescope picker, you would see the list of files/directories in the preview. The tricky part would be to define when exactly the scope should be updated. Most likely, just before returning from get_current_dirs(), this callback should be invoked so that we have the "freshest" scope definition before searching for files or grepping.

I think these two generic features would be the ground for the new use case. Regarding whether the list of changed files should be a part of the plugin itself or a user customization, I don't have a hard preference. If this is an optionally enabled feature, something like `require("neoscopes").add_git_changed_files_scope()`, I guess there is no reason why it can't be provided out of the box. 

The same goes for the workspaces in package.json.

I will get to these features in a while. Thanks again for bringing this up.

**Comment by defr0std** [comment]
Thank you, @napisani, for adding support for this in #5.
